app/views/misc_views.py
# Copyright 2014 SolidBuilds.com. All rights reserved
#
# Authors: Ling Thio <ling.thio@gmail.com>


from flask import Blueprint, redirect, render_template
from flask import request, url_for
from flask_user import current_user, login_required, roles_required

from app import db
from app.models.user_models import UserProfileForm

main_blueprint = Blueprint('main', __name__, template_folder='templates')

# The Home page is accessible to anyone
@main_blueprint.route('/')
def home_page():
    return render_template('pages/home_page.html')


# The User page is accessible to authenticated users (users that have logged in)
@main_blueprint.route('/member')
@login_required  # Limits access to authenticated users
def member_page():
    return render_template('pages/user_page.html')


# The Admin page is accessible to users with the 'admin' role
@main_blueprint.route('/admin')
@roles_required('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('pages/admin_page.html')


@main_blueprint.route('/pages/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, obj=current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('main.home_page'))

    # Process GET or invalid POST
    return render_template('pages/user_profile_page.html',
                           form=form)

app/templates/pages/admin_page.html
{% extends "layout.html" %}

{% block content %}
<script type="text/javascript" class="init">
    $(document).ready(function () {
        // Define custom table columns and add them to general data columns
        let columns = [
            {
                name: 'status', data: null, render: function (data) {
                    return createStatusLabel(data, true);
                }
            },
            {
                data: null,
                render: createUserAssignSelect
            },
            {
                data: null,
                render: createSplitAssignSelect
            },
            {
                data: null,
                render: function (data, type, row) {
                    return '<button class="btn btn-primary segmentationUploadButton">Upload</button> ' +
                        '<button style="margin-left: 30px; margin-right: 30px;" class="btn btn-primary dataDownloadButton">Download</button>' +
                        '<button class="btn btn-add rowDeleteButton"><i class="fa fa-trash" style="font-size:36px;"></i></button>';
                }
            },
        ];
        generalTable["columns"] = generalTable["columns"].concat(columns);

        // Initialize table
        $('#datatable').DataTable(generalTable);

        // Register add data button
        $('#imageUploadModalButton').click(function () {
            let table = $('#datatable').DataTable();
            let projectObj = table.ajax.json()["project"];
            showImageUploadModal(projectObj);
        });


        // Make sure that every time an assignment is changed, an update is sent to the server
        $('#datatable').on('draw.dt', function () {
            registerDatatableElements()
        });
    });

</script>
<table id="datatable" class="table table-striped table-hover dt-responsive nowrap">
    <thead>
    <tr>
        <th></th>
        <th> Name</th>
        <th> Patient Name</th>
        <th> Modality</th>
        <th> Contrast Type</th>
        <th> Accession Number</th>
        <th> Insert Date</th>
        <th> Last Updated</th>
        <th> Last Message</th>

        <th> Status</th>
        <th> Assign</th>
        <th> Split</th>
        <th> Data</th>
    </tr>
    </thead>
</table>

<button class="btn btn-primary" id="imageUploadModalButton">Upload Image</button>
{% endblock %}

{% block forms %}
{% include 'forms/image_upload_form.html' %}
{% include 'forms/segmentation_upload_form.html' %}
{% include 'forms/download_form.html' %}
{% endblock %}

app/templates/pages/home_page.html
{% extends "common/page_base.html" %}

{% block content %}
    <h2>{%trans%}Home page{%endtrans%}</h2>
    <p><a href={{ url_for('user.register') }}>{%trans%}Register{%endtrans%}</a></p>
    <p><a href={{ url_for('user.login') }}>{%trans%}Sign in{%endtrans%}</a></p>
    <p><a href={{ url_for('main.home_page') }}>{%trans%}Home Page{%endtrans%}</a> (accessible to anyone)</p>
    <p><a href={{ url_for('main.member_page') }}>{%trans%}Member Page{%endtrans%}</a> (login_required: member@example.com / Password1)</p>
    <p><a href={{ url_for('main.admin_page') }}>{%trans%}Admin Page{%endtrans%}</a> (roles_required: admin@example.com / Password1)</p>
    <p><a href={{ url_for('user.logout') }}>{%trans%}Sign out{%endtrans%}</a></p>
{% endblock %}

app/templates/pages/project_overview.html
{% extends "layout.html" %}
{% block content %}
<script type="module" class="init">
    $(document).ready(function () {
        // Table definition
        $('#project_overview_table').DataTable({
            ajax: {
                url: "/api/project/all",
                dataSrc: 'projects'
            },
            columns: [
                {
                    data: null,
                    render: function (data) {
                        return '<button class="btn btn-success chooseProjectButton">Choose</button>';
                    }
                },
                {data: 'short_name'},
                {data: 'long_name'},
                {
                    data: null,
                    render: function (data) {
                        return '<button class="btn btn-primary editProjectButton">Settings</button>';
                    }
                },

            ],
            columnDefs: [{"className": "dt-center", "targets": "_all"}],
            autoWidth: false
        });

        // Handle interactions with the table and its elements
        $('#project_overview_table').on('draw.dt', function () {
            // Choose button
            $('.chooseProjectButton').click(function () {
                // Get project object of this row
                let table = $('#project_overview_table').DataTable();
                let row = $(this).closest('tr');
                let rowObject = table.row(row).data();

                // Find project id and redirect to correct page
                let projectID = rowObject['id'];
                window.location.replace("/project/" + projectID)
            });

            // Edit button
            $('.editProjectButton').click(function () {
                // Get project object of this row
                let table = $('#project_overview_table').DataTable();
                let row = $(this).closest('tr');
                let projectObject = table.row(row).data();

                $.get({
                    url: "/api/user/all"
                }).then(response => {
                    show_project_modal(projectObject, response.users);
                })

                
            });

            // New project
            $('#addProjectButton').click(function () {
                $.get({
                    url: "/api/user/all"
                }).then(response => {
                    show_project_modal(null, response.users)
                })
                
            });
        });
    });

</script>
<div>
    <h1>Project Overview</h1>
    <table id="project_overview_table" class="table table-striped table-hover dt-responsive nowrap">
        <thead>
        <tr>
            <th> Project</th>
            <th> Short Name</th>
            <th> Long Name</th>
            <th> Edit</th>
        </tr>
        </thead>
    </table>

    <div>
        {% if is_technical_admin %}
        <button class="btn btn-primary" id="addProjectButton">Add Project</button>
        {% endif %}
        <button class="btn btn-primary" id="addUsersButton" onclick="window.location.href = '/users'">Users</button>
    </div>

</div>
{% endblock %}

{% block forms %}
{% include 'forms/project_configuration_form.html' %}
{% endblock %}

app/templates/pages/projects_overview.html
{% extends "layout.html" %}
{% block content %}
<script type="module" class="init">
    $(document).ready(function () {
        // Table definition
        $('#projects_overview_table').DataTable({
            ajax: {
                url: "/data/projects_overview",
            },
            columns: [
                {
                    data: null,
                    render: function (data) {
                        return '<button class="btn btn-success chooseProjectButton">Choose</button>';
                    }
                },
                {data: 'short_name'},
                {data: 'long_name'},
                {
                    data: null,
                    render: function (data) {
                        return '<button class="btn btn-primary editProjectButton">Settings</button>';
                    }
                },

            ],
            columnDefs: [{"className": "dt-center", "targets": "_all"}],
            autoWidth: false
        });

        // Handle interactions with the table and its elements
        $('#projects_overview_table').on('draw.dt', function () {
            // Choose button
            $('.chooseProjectButton').click(function () {
                // Get project object of this row
                let table = $('#projects_overview_table').DataTable();
                let row = $(this).closest('tr');
                let rowObject = table.row(row).data();

                // Find project id and redirect to correct page
                let projectID = rowObject['id'];
                window.location.replace("/projects/" + projectID)
            });

            // Edit button
            $('.editProjectButton').click(function () {
                // Get project object of this row
                let table = $('#projects_overview_table').DataTable();
                let row = $(this).closest('tr');
                let projectObject = table.row(row).data();
                let allUsers = table.ajax.json()["users"];

                show_project_modal(projectObject, allUsers);
            });

            // New project
            $('#addProjectButton').click(function () {
                let table = $('#projects_overview_table').DataTable();
                let allUsers = table.ajax.json()["users"];
                show_project_modal(null, allUsers)
            });
        });
    });

</script>
<div>
    <h1>Project Overview</h1>
    <table id="projects_overview_table" class="table table-striped table-hover dt-responsive nowrap">
        <thead>
        <tr>
            <th> Project</th>
            <th> Short Name</th>
            <th> Long Name</th>
            <th> Edit</th>
        </tr>
        </thead>
    </table>

    <div>
        <button class="btn btn-primary" id="addProjectButton">Add Project</button>
        <button class="btn btn-primary" id="addUsersButton" onclick="window.location.href = '/users';">Users</button>
    </div>

</div>
{% endblock %}

{% block forms %}
{% include 'forms/project_configuration_form.html' %}
{% endblock %}

app/templates/pages/review_page.html
{% extends "layout.html" %}

{% block content %}
<script type="text/javascript" class="init">

    $(document).ready(function () {
        // Table definition
        let columns = [
            {name: 'status', data: null, render: function(data){return createStatusLabel(data, false);}},
            {
                data: null,
                render: createUserAssignSelect
            },
            {
                data: null,
                render: createSplitAssignSelect
            },
            {
                data: null,
                render: function (data, type, row) {
                    return '<button class="btn btn-danger reviewButton">Review</i></button>';
                }
            },
            {
                data: null,
                render: function (data, type, row) {
                    return '<button style="margin-left: 30px" class="btn btn-primary dataDownloadButton">Download</button>';

                }
            },

        ];

        // Initialize table
        generalTable["columns"] = generalTable["columns"].concat(columns);
        $('#datatable').DataTable(generalTable);

        // Buttons/checkboxes functionality
        $('#datatable').on('draw.dt', function () {
            registerDatatableElements();
        });

    });

</script>
<table id="datatable" class="table table-striped table-hover dt-responsive nowrap">
    <thead>
    <tr>
        <th></th>
        <th> Name</th>
        <th> Patient Name</th>
        <th> Modality</th>
        <th> Contrast Type</th>
        <th> Accession Number</th>
        <th> Insert Date</th>
        <th> Last Updated</th>
        <th> Last Message</th>

        <th> Status</th>
        <th> Assign</th>
        <th> Split</th>
        <th> Review</th>
        <th> Data</th>
    </tr>
    </thead>
</table>

{% endblock %}

{% block forms %}
{% include 'forms/review_form.html' %}
{% include 'forms/download_form.html' %}
{% endblock %}

app/templates/pages/segmentation_page.html
{% extends "layout.html" %}

{% block content %}
<script type="text/javascript" class="init">


    $(document).ready(function () {
        let columns = [
            {
                name: 'status',
                data: null,
                render: function (data) {
                    return createStatusLabel(data, false);
                }
            },
            {
                data: null,
                render: function (data, type, row) {
                    return '<button class="btn btn-primary segmentationUploadButton">Upload</button> ' +
                        '<button style="margin-left: 30px; margin-right: 30px;" class="btn btn-primary dataDownloadButton">Download</button>';
                }
            },

        ];
        generalTable["columns"] = generalTable["columns"].concat(columns);

        // Initialize table
        $('#datatable').DataTable(generalTable);


        $('#datatable').on('draw.dt', function () {
            // Upload new segmentations
            $('.segmentationUploadButton').click(function () {
                let table = $('#datatable').DataTable();
                let rowObject = table.row($(this).closest('tr')).data();
                showSegmentationUploadModal(rowObject);
            });

            // Download data
            $('.dataDownloadButton').click(function () {
                let table = $('#datatable').DataTable();
                let rowObject = table.row($(this).closest('tr')).data();
                showDownloadModal(rowObject);
            });
        });
    });

</script>
<table id="datatable" class="table table-striped table-hover dt-responsive nowrap">
    <thead>
    <tr>
        <th></th>
        <th> Name</th>
        <th> Patient Name</th>
        <th> Modality</th>
        <th> Contrast Type</th>
        <th> Accession Number</th>
        <th> Insert Date</th>
        <th> Last Updated</th>
        <th> Last Message</th>

        <th> Status</th>
        <th> Data</th>
    </tr>
    </thead>
</table>

{% endblock %}

{% block forms %}
{% include 'forms/segmentation_upload_form.html' %}
{% include 'forms/download_form.html' %}
{% endblock %}

app/templates/pages/user_page.html
{% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}
    <h2>{%trans%}Members page{%endtrans%}</h2>
    <p><a href={{ url_for('user.register') }}>{%trans%}Register{%endtrans%}</a></p>
    <p><a href={{ url_for('user.login') }}>{%trans%}Sign in{%endtrans%}</a></p>
    <p><a href={{ url_for('main.home_page') }}>{%trans%}Home Page{%endtrans%}</a> (accessible to anyone)</p>
    <p><a href={{ url_for('main.member_page') }}>{%trans%}Member Page{%endtrans%}</a> (login_required: member@example.com / Password1)</p>
    <p><a href={{ url_for('main.admin_page') }}>{%trans%}Admin Page{%endtrans%}</a> (roles_required: admin@example.com / Password1)</p>
    <p><a href={{ url_for('user.logout') }}>{%trans%}Sign out{%endtrans%}</a></p>
{% endblock %}

app/templates/pages/user_profile_page.html
{% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}
<h1>User Profile</h1>

<p><a href="{{ url_for('user.change_password') }}">Change password</a></p>

{% from "common/form_macros.html" import render_field, render_submit_field %}
<form action="" method="POST" class="form" role="form">
  <div class="row">
    <div class="col-sm-6 col-md-5 col-lg-4">
    {{ form.hidden_tag() }}

    {{ render_field(form.first_name, tabindex=240) }}

    {{ render_field(form.last_name, tabindex=250) }}

    {{ render_submit_field(form.submit, tabindex=280) }}
    </div>
  </div>
</form>

{% endblock %}

app/templates/pages/users_page.html
{% extends "layout.html" %}

{% block content %}
<script type="text/javascript" class="init">
    $(document).ready(function () {
        let datatableDefinition = {
            ajax: {url: "/api/user/all",
            dataSrc: "users"},
            columns: [
                {name: 'First Name', data: 'first_name'},
                {name: 'Last Name', data: 'last_name'},
                {name: 'Email', data: 'email'},
                {
                    data: null,
                    render: function (data, type, row) {
                        {% if is_technical_admin %}
                            if(data.id != user_id) {
                                return '<button class="btn btn-add deleteUserButton"><i class="fa fa-trash" style="font-size:36px;"></i></button>'
                            } else {
                                return "";
                            }
                        {% else %}
                            return "";
                        {% endif %}
                    }
                },
            ],
            columnDefs: [{"className": "dt-center", "targets": "_all"}],
            autoWidth: false
        };
        $('#userDatatable').DataTable(datatableDefinition);
        $('#userDatatable').on('draw.dt', function () {
            // Delete User functionality
            $('.deleteUserButton').click(function () {
                let table = $('#userDatatable').DataTable();
                let userObject = table.row($(this).closest('tr')).data();
                console.log(userObject);

                $.ajax({
                    url: '/api/user?id=' + userObject["id"],
                    type: 'DELETE',
                    success: function (data) {
                        $('#userDatatable').DataTable().ajax.reload();
                        //location.reload();
                    },
                    error: function (e) {
                        console.log(e);
                    },
                });
            });

            // Add new users
            $('#addUserButton').click(function () {
                showNewUserModal();
            });
        });

    });

</script>
<h1>Users Overview</h1>
<table id="userDatatable" class="table table-striped table-hover dt-responsive nowrap">
    <thead>
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Delete</th>
    </tr>
    </thead>
</table>

{% if is_technical_admin %}
<button class="btn btn-primary" id="addUserButton">Add User</button>
{% endif %}

{% endblock %}

{% block forms %}
{% include 'forms/new_user.html' %}
{% endblock %}